/home/mcaskey/10XvParse/Data/Analysis_6/10x/FASTA/Processed/10x_0.fastq.gz: 450991405
/home/mcaskey/10XvParse/Data/Analysis_6/parse/FASTA/Processed/parse_0.fastq.gz: 405441287
/home/mcaskey/10XvParse/Data/Analysis_6/parse/FASTA/Processed/polyT_0.fastq.gz: 240606702
/home/mcaskey/10XvParse/Data/Analysis_6/parse/FASTA/Processed/randO_0.fastq.gz: 164834585
