/home/mcaskey/10XvParse/Data/Analysis_2/10x/FASTA/Processed/10x_0.fastq.gz: 639108133
/home/mcaskey/10XvParse/Data/Analysis_2/parse/FASTA/Processed/parse_0.fastq.gz: 1840890610
/home/mcaskey/10XvParse/Data/Analysis_2/parse/FASTA/Processed/polyT_0.fastq.gz: 853704130
/home/mcaskey/10XvParse/Data/Analysis_2/parse/FASTA/Processed/randO_0.fastq.gz: 987186480
/home/mcaskey/10XvParse/Data/Analysis_2/parse_mini/FASTA/Processed/parse_mini_0.fastq.gz: 405124522
/home/mcaskey/10XvParse/Data/Analysis_2/parse_mini/FASTA/Processed/polyT_0.fastq.gz: 188781476
/home/mcaskey/10XvParse/Data/Analysis_2/parse_mini/FASTA/Processed/randO_0.fastq.gz: 216343046
