/home/mcaskey/10XvParse/Data/Analysis_3/10x_H1/FASTA/Processed/10x_H1_0.fastq.gz: 203134663
/home/mcaskey/10XvParse/Data/Analysis_3/10x_H2/FASTA/Processed/10x_H2_0.fastq.gz: 254103388
/home/mcaskey/10XvParse/Data/Analysis_3/parse_H1/FASTA/Processed/parse_H1_0.fastq.gz: 246160467
/home/mcaskey/10XvParse/Data/Analysis_3/parse_H1/FASTA/Processed/polyT_0.fastq.gz: 157044013
/home/mcaskey/10XvParse/Data/Analysis_3/parse_H1/FASTA/Processed/randO_0.fastq.gz: 89116454
/home/mcaskey/10XvParse/Data/Analysis_3/parse_H2/FASTA/Processed/parse_H2_0.fastq.gz: 233550592
/home/mcaskey/10XvParse/Data/Analysis_3/parse_H2/FASTA/Processed/polyT_0.fastq.gz: 135417275
/home/mcaskey/10XvParse/Data/Analysis_3/parse_H2/FASTA/Processed/randO_0.fastq.gz: 98133317
