/home/mcaskey/10XvParse/Data/Analysis_7/10x/FASTA/Processed/10x_0.fastq.gz: 1498786991
/home/mcaskey/10XvParse/Data/Analysis_7/parse/FASTA/Processed/parse_0.fastq.gz: 13626157
/home/mcaskey/10XvParse/Data/Analysis_7/parse/FASTA/Processed/polyT_0.fastq.gz: 8329621
/home/mcaskey/10XvParse/Data/Analysis_7/parse/FASTA/Processed/randO_0.fastq.gz: 5296536
