/home/mcaskey/10XvParse/Data/Analysis_7/10x/FASTA/Processed/10x_0.fastq.gz: 1498786991
/home/mcaskey/10XvParse/Data/Analysis_7/parse/FASTA/Processed/parse_0.fastq.gz: 843080221
/home/mcaskey/10XvParse/Data/Analysis_7/parse/FASTA/Processed/polyT_0.fastq.gz: 339037087
/home/mcaskey/10XvParse/Data/Analysis_7/parse/FASTA/Processed/randO_0.fastq.gz: 504043134
