/home/mcaskey/10XvParse/Data/Analysis_4/10x/FASTA/Processed/10x_0.fastq.gz: 207160711
/home/mcaskey/10XvParse/Data/Analysis_4/parse/FASTA/Processed/parse_0.fastq.gz: 30726743
/home/mcaskey/10XvParse/Data/Analysis_4/parse/FASTA/Processed/polyT_0.fastq.gz: 14026910
/home/mcaskey/10XvParse/Data/Analysis_4/parse/FASTA/Processed/randO_0.fastq.gz: 16699833
