/home/mcaskey/10XvParse/Data/Analysis_5/10x/FASTA/Processed/10x_0.fastq.gz: 457238051
/home/mcaskey/10XvParse/Data/Analysis_5/10x_1/FASTA/Processed/10x_1_0.fastq.gz: 203134663
/home/mcaskey/10XvParse/Data/Analysis_5/10x_2/FASTA/Processed/10x_2_0.fastq.gz: 254103388
/home/mcaskey/10XvParse/Data/Analysis_5/parse/FASTA/Processed/parse_0.fastq.gz: 130861556
/home/mcaskey/10XvParse/Data/Analysis_5/parse/FASTA/Processed/polyT_0.fastq.gz: 66306807
/home/mcaskey/10XvParse/Data/Analysis_5/parse/FASTA/Processed/randO_0.fastq.gz: 64554749
