name: Analysis_5

SRA:
 10x:
 - SRR26594154
 - SRR26594153
 parse:
  sub1:
  - SRR28867558

# The suffix for the R1 and R2 FASTA files dumped from fasterq-dump. For some reason these change across datasets
read_num:
  10x:
    R1: 1
    R2: 2
  parse:
    R1: 2
    R2: 3

# Files to generate the kallisto index
species: human

# The kb-python technology strings
tech:
 10x: 10XV3
 parse: WT_v2